### ISSUE TITLE
How to Configure/Edit Drives

### ISSUE THREAD

**Issue by ghost** [Syzygianinfern0/RClone-Mirror-Manager#1]

**Comment by Syzygianinfern0** [comment]
You need to edit these lines so that they are the rclone drive names. 

https://github.com/Syzygianinfern0/RClone-Mirror-Manager/blob/9a10b09e1c83b7a62858522220b70dbaaad6f51e/sync.py#L5-L21

**Comment by Syzygianinfern0** [comment]
Yes

**Comment by ghost** [comment]
What if i have two drives and i need to copy from Main Drive to Backup Drive

Should i Edit like this

 from_drives = [ 
     "Main Drive",
 ] 
 to_drives = [ 
     "Backup Drive",
 ]

**Comment by Syzygianinfern0** [comment]
Yes

**Comment by ghost** [comment]
Thanks Alot

**Comment by ghost** [comment]
But what if i just need to copy a folder from Main Drive to Backup Drive

**Comment by Syzygianinfern0** [comment]
In your rclone config for main drive, you can put the folder ID you want in the `root_folder_id` key. 

For example, if your drive link for the folder is `https://drive.google.com/drive/folders/XYZ`, you can put in `root_folder_id = XYZ` in the rclone config.

**Comment by ghost** [comment]
Ok Thanks alot Bro i needed it madly, Final Question How Much Speed it Will Transfer my Files.And Sorry for Asking So Many Questions Na.

**Comment by Syzygianinfern0** [comment]
The code uses `rclone --drive-server-side-across-configs`. So the transfers would be almost instantaneous for large files. But if you have a lot of small files, the transfer is somewhat slow. 

Although I think you might never need to worry about the transfer speed - the script would always do its job.

**Comment by ghost** [comment]
Great Job 👍

**Comment by ghost** [comment]
Thanks 😊

**Comment by ghost** [comment]
Bro Do U Have any idea about telegram mirror bots

**Comment by Syzygianinfern0** [comment]
https://t.me/TorrentBots

I think you would many groups here.

**Comment by ghost** [comment]
No i have bot but i need someone's help to tweak something but i am just 16 years old boy from TN and i don't know anyone, So Thought to Ask Some Help From You.

**Comment by ghost** [comment]
I Still Learning Python, Beginning I Checked the code but everything is apart from my knowledge.

**Comment by Syzygianinfern0** [comment]
I think getting in touch with support groups of specific bots would be more helpful to you rather than me personally.

**Comment by ghost** [comment]
Ohh, There Are Not Replying very slow sometimes there don't even care but it's ok not A problem bro,But Thanks Alot
