### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [Syzygianinfern0/RClone-Mirror-Manager#2]
Warning: 8 15:55:31,376 RClone [WARNING]: Failed to create file system for "Backup Drive_1:sync/": didn't find section in config file

**Comment by Syzygianinfern0** [comment]
Your rclone config is not set up properly. As the error says: `didn't find section in config file`. Make sure you have an entry for `Backup Drive_1` in your config file.

**Comment by ghost** [comment]
Yep

**Comment by ghost** [comment]
It's working bro

**Comment by ghost** [comment]
But with a problem

**Comment by ghost** [comment]
This Works Where I only backup to single drive from main drive
from_drives = [
    "Main Drive",
]
to_drives = [
    "Backup Drive_1",
]


It gives me that error when I set it to backup to three different drives from main drive

from_drives = [
    "Main Drive",
]
to_drives = [
    "Backup Drive_1",
    "Backup Drive_2",
    "Backup Drive_2",
]

**Comment by Syzygianinfern0** [comment]
Not sure what the error could be in that case. Make sure you carefully check the config file is working locally using rclone commands.

**Comment by ghost** [comment]
But R U Sure This below Config is Correct

from_drives = [
"Main Drive",
]
to_drives = [
"Backup Drive_1",
"Backup Drive_2",
"Backup Drive_2",
]

**Comment by Syzygianinfern0** [comment]
If there is any error from python side, it would show up as a python error directly in your actions log. As such, there doesn't seem to be any error. Make sure you check the names of the drives between the rclone configs and sync.py lists match correctly.

**Comment by ghost** [comment]
Mm
