### ISSUE TITLE
How Can We Add SA To Skip 750gb Limit

### ISSUE THREAD

**Issue by ghost** [Syzygianinfern0/RClone-Mirror-Manager#3]

**Comment by Syzygianinfern0** [comment]
The current status of the repo does not support using SAs. Please do feel free to implement the feature and send in a PR.

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
Hmm i Am Researching That Only, if this Repo has That SA It's Unstoppable

**Comment by ghost** [comment]
I Try My Best bro

**Comment by ghost** [comment]
I was thinking y files not copying anymore than i saw the total drive size it said 740gb, And i am " ok Limit over " 😂

**Comment by ZekXtreme** [comment]
You can't use SA until you use gclone or fclone

**Comment by ghost** [comment]
Yep, That's Wt I Ended Up Finding Those AutoRClone, Gclone ...etc

**Comment by ghost** [comment]
Update! I Tried with AutoRClone and it's Working To Be Honest but it has been running for 3 hours

**Comment by ghost** [comment]
Hi Syzygianinfern0, I Want to Know Weather This Repo Support Other Cloud Transfer, r only Drive To Drive (server side copy)

**Comment by Syzygianinfern0** [comment]
What do you mean other clone transfer?

**Comment by ghost** [comment]
Like Google drive to Dropbox,Mega,One Drive R Cloud Available in Rclone

**Comment by Syzygianinfern0** [comment]
You can probably run it

**Comment by ZekXtreme** [comment]
> Hi Syzygianinfern0, I Want to Know Weather This Repo Support Other Cloud Transfer, r only Drive To Drive (server side copy)

@BlackFoxy616 u cant run server side transfer for drive to other service

**Comment by Syzygianinfern0** [comment]
> You can probably run it

Ah my bad. I didn't see the "server side". Thanks @ZekXtreme.

**Comment by Syzygianinfern0** [comment]
@BlackFoxy616 SA support is added
