### ISSUE TITLE
Assert len(sa_files) AssertionError

### ISSUE THREAD

**Issue by ghost** [Syzygianinfern0/RClone-Mirror-Manager#5]
Traceback (most recent call last):
  File "sync.py", line 29, in <module>
    assert len(sa_files)
AssertionError

**Comment by Syzygianinfern0** [comment]
Please follow the instructions to set up the accounts as given in https://github.com/Syzygianinfern0/RClone-Mirror-Manager#using-service-accounts-optional

**Comment by ghost** [comment]
I followed

**Comment by Syzygianinfern0** [comment]
Ur zip folder is probably not set up properly

**Comment by Syzygianinfern0** [comment]
Closing as issue is due to improper setup.
