### ISSUE TITLE
can i see example of rclone.conf ? mine does not use service accounts even i zipped a folder contains 100 .jsons

### ISSUE THREAD

**Issue by KenZync** [Syzygianinfern0/RClone-Mirror-Manager#6]
It so slow that only main account is transfering, any idea?

**Comment by Syzygianinfern0** [comment]
I don't have anything special in my rclone config. Anyways, here is a redacted version of what I use. 

```
[1]
type = drive
client_id = redacted.apps.googleusercontent.com
client_secret = redacted
scope = drive
token = {"access_token":"reacted","token_type":"Bearer","refresh_token":"redacted","expiry":"2021-05-20T08:20:42.794834932+05:30"}
team_drive = redacted__3f517Uk9PVA
root_folder_id = 
```

**Comment by KenZync** [comment]
Do the service accounts should be run simutaneously? it's been 2 hours now just a data of ~100gb with 10k+ files

**Comment by Syzygianinfern0** [comment]
No, the service accounts are ONLY to escape the limit of 750 GB per day. There isn't really any _parallel processing_ done by the SAs. The code just uses [GClone](https://github.com/dogbutcat/gclone) which provides dynamic replacement sa file support. 

It is expected to be slow (no matter what way you are copying things over) if you have many many small size files.

**Comment by KenZync** [comment]
Ok I see now, thankyou.
